### PR TITLE
feat(add): Add Apple Secret generation

### PR DESCRIPTION
**Pull request by serhiyhvala**
Generate `client_secret` for Apple Provider

## ℹ️ More Details
[Link to thread in X](https://x.com/serhiyhvala/status/1813483675612225630)

Apple Client secrets are special :sparkles:

They require the developer to collect the following values from the Apple Developer dashboard:

- Team ID (pasted from clipboard)
- Key ID (pasted from clipboard)
- Client ID (pasted from clipboard)
- Private Key (the developer needs to provide a path to the `.p8` file.)

Then, a JWT is constructed with an optional expiration date (180 days from now by default) which will be then saved as `AUTH_APPLE_SECRET`.

More details: https://developer.apple.com/documentation/accountorganizationaldatasharing/creating-a-client-secret

## 🧢 Checklist

- [x] Documentation
- [ ] Ready to be merged

## 📌 Resources

- [Security guidelines](https://github.com/nextauthjs/.github/blob/main/SECURITY.md)
- [Contributing guidelines](https://github.com/nextauthjs/.github/blob/main/CONTRIBUTING.md)
- [Code of conduct](https://github.com/nextauthjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [Contributing to Open Source](https://kcd.im/pull-request)

### CODE REVIEW

**Review by JoftheV — APPROVED** [review]

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
Thank you! Sorry that it took this long. :see_no_evil:

**Comment by hanzalaansari** [comment]
so now we do not need to genrate the secret from here https://generate-client-secret.vercel.app/
will it gen automatically 
AppleProvider({
      clientId: process.env.APPLE_CLIENT_ID,
      clientSecret: {
        teamId: process.env.APPLE_TEAM_ID, 
        privateKey: process.env.APPLE_PRIVATE_KEY?.replace(/\\n/g, "\n"), 
        keyId: process.env.APPLE_KEY_ID, 
      },
    }),
  ],
  @balazsorban44

**Comment by hanzalaansari** [comment]
@balazsorban44 getting 500 Internal Server Error.

**Comment by balazsorban44** [comment]
hi, no. you still need to generate the secret at build time, given the variables Apple requires

**Pull request merged**
